-- 0007_reset_explanation_cache.sql
-- The explanation + theory prompts were rewritten to demand concrete rules
-- (deciding word, numeric limits, the inverted sentence) instead of generic
-- "follow the Codice della Strada" filler. Cached rows were generated by the
-- old prompts, so they'd keep serving the vague text forever — clear them and
-- let them regenerate lazily on next view.
--
-- translated_text is NOT cleared: translations were fine and re-generating
-- ~7k of them costs real money.

UPDATE translations_cache SET explanation = NULL, theory_text = NULL;
